#!/bin/bash

# گرفتن تعداد آپدیت‌ها
updates=$(checkupdates 2> /dev/null | wc -l)

# تعیین کلاس بر اساس تعداد
if [ "$updates" -gt 50 ]; then
    class="critical"
elif [ "$updates" -gt 0 ]; then
    class="pending"
else
    class="updated"
fi

# خروجی به فرمت JSON برای Waybar
printf '{"text": "%s", "alt": "%s", "tooltip": "%s", "class": "%s"}\n' "$updates" "$updates" "$updates" "$class"