TS_SEARCH_PATHS=(~/projects/github ~/projects/side ~/projects/global ~/projects/tools/ ~/projects/others ~/dots/*/.config)
TS_MAX_DEPTH=1

DAILY_PATH="$HOME/Notes/04 - Planner/Daily Notes/$(date +%Y)/$(date +%m)/$(date +%Y-%m-%d).md"

# 3. Reference the variable inside the array
TS_SESSION_COMMANDS=(
    "claude ." 
    "codex ." 
    "gemini ." 
    "nvim '$DAILY_PATH'"
)
