# Autostart necessary processes (notifications daemons, status bars, etc.)
exec-once = echo "Xft.dpi: 144" | xrdb -merge
exec-once = nm-applet &
exec-once = waybar & swww-daemon & swaync
exec-once = systemctl --user start hyprpolkitagent
exec-once = 1password --silent
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
