# Autostart necessary processes (notifications daemons, status bars, etc.)

# System
exec-once = echo "Xft.dpi: 144" | xrdb -merge
exec-once = wl-paste --type image --watch cliphist store
exec-once = wl-paste --type text --watch cliphist store
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user start hyprpolkitagent
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = hypridle


# Desktop
exec-once = waybar &
exec-once = swww-daemon &
exec-once = swaync &
exec-once = nm-applet &

# Applications
exec-once = 1password --silent
exec-once = obsidian --silent
exec-once = easyeffects --silent
