general {
    lock_cmd = pidof hyprlock || hyprlock       # دستور اجرای لاکر
    before_sleep_cmd = loginctl lock-session    # قفل کردن قبل از ساسپند
    after_sleep_cmd = hyprctl dispatch dpms on  # روشن کردن مانیتور بعد از بیدار شدن
}

listener {
    timeout = 300                                # بعد از ۵ دقیقه (۳۰۰ ثانیه)
    on-timeout = loginctl lock-session           # سیستم را قفل کن
}

listener {
    timeout = 330                                # بعد از ۵.۵ دقیقه
    on-timeout = hyprctl dispatch dpms off       # مانیتور را خاموش کن
    on-resume = hyprctl dispatch dpms on         # با حرکت موس روشن کن
}
