# See https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = us,ir
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1
    sensitivity = 0
    numlock_by_default = false
    kb_options = lv5:caps_switch

    touchpad {
        natural_scroll = false
    }
}

# See https://wiki.hypr.land/Configuring/Gestures
gesture = 3, horizontal, workspace

# Per-device config
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
