# See https://wiki.hypr.land/Configuring/Keywords/
$terminal = ghostty
$fileManager = dolphin
$menu = $HOME/.config/rofi/launchers/type-2/launcher.sh || pkill rofi

$mainMod = SUPER
$hyper = SHIFT CTRL ALT SUPER


$mainTermClass = robco.terms.main
$floatingTermClass = robco.terms.floating
