# See https://wiki.hypr.land/Configuring/Window-Rules/
# See https://wiki.hypr.land/Configuring/Workspace-Rules/

workspace = 3, rounding:false, decorate:false


xwayland {
    force_zero_scaling = true
}

windowrule {
  name = mainTerm
  workspace = 1
  match:class = ^($mainTermClass)$
}

windowrule {
  name = floatingTerm
  match:title = ^($floatingTermClass)$
  float = true
  size = 800 900
  center = true
  border_size = 2
  rounding = 8
  rounding_power = 1
}

windowrule {
  name = satty
  match:class = com.gabm.satty
  float = true
  center = true
  rounding = 8
  rounding_power = 2
  size = 60% 60%
}

windowrule {
  name = cursor
  workspace = 3
  match:class = ^(cursor)$
  group = true
}

windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}

layerrule {
    name = rofi-blur
    match:namespace = ^(rofi)$
    blur = on
    ignore_alpha = 0
    xray = off
}

layerrule {
    name = waybar-blur
    match:namespace = ^(waybar)$
    blur = on
    ignore_alpha = 0
    xray = off
}

windowrule {
    name = waypaper-float
    match:class = waypaper
    float = yes
    center = yes
    size = 900 600
}

experimental {
}
