"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

[manager]
# cwd = { fg = "#43677F" }
#
# hovered         = { fg = "#43677F", bg = "#0E0E0F", bold = true, underline = true }
# preview_hovered = { underline = true }
#
# find_keyword  = { fg = "#456382", italic = true }
# find_position = { fg = "#55559D", bg = "reset", italic = true }
#
# marker_selected = { fg = "#456382", bg = "#456382" }
# marker_copied   = { fg = "#456382", bg = "#456382" }
# marker_cut      = { fg = "#43677F", bg = "#43677F" }
#
# tab_active   = { fg = "#0E0E0F", bg = "#A2A2A2" }
# tab_inactive = { fg = "#A2A2A2", bg = "#0E0E0F" }
# tab_width    = 1
#
border_style  = { fg = "#E27BE2" }

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#0E0E0F", bg = "#0E0E0F" }

mode_normal = { fg = "#0E0E0F", bg = "#43677F", bold = true }
mode_select = { fg = "#0E0E0F", bg = "#456382", bold = true }
# mode_unset  = { fg = "#0E0E0F", bg = "#E27BE2", bold = true }
#
# progress_label  = { fg = "#F5F4F5", bold = true }
# progress_normal = { fg = "#A2A2A2", bg = "#0E0E0F" }
# progress_error  = { fg = "#43677F", bg = "#0E0E0F" }
#
# permissions_t = { fg = "#A2A2A2" }
# permissions_r = { fg = "#456382" }
# permissions_w = { fg = "#43677F" }
# permissions_x = { fg = "#456382" }
# permissions_s = { fg = "#A2A2A2" }

# [input]
# border   = { fg = "#456382" }
# title    = {}
# value    = {}
# selected = { reversed = true }
#
# [select]
# border   = { fg = "#A2A2A2" }
# active   = { fg = "#55559D" }
# inactive = {}
#
# [tasks]
# border  = { fg = "#A2A2A2" }
# title   = {}
# hovered = { underline = true }
#
# [which]
# mask            = { bg = "#0E0E0F" }
# cand            = { fg = "#F5F4F5" }
# rest            = { fg = "#A2A2A2" }
# desc            = { fg = "#55559D" }
# separator       = "  "
# separator_style = { fg = "#A2A2A2" }
#
# [help]
# on      = { fg = "#55559D" }
# exec    = { fg = "#F5F4F5" }
# desc    = { fg = "#A2A2A2" }
# hovered = { bg = "#A2A2A2", bold = true }
# footer  = { fg = "#0E0E0F", bg = "#A2A2A2" }
#
# [filetype]
# rules = [
#     { mime = "image/*", fg = "#E27BE2" },
#
#     { mime = "video/*", fg = "#6969C0" },
#     { mime = "audio/*", fg = "#456382" },
#
#     { mime = "application/zip",             fg = "#55559D" },
#     { mime = "application/gzip",            fg = "#55559D" },
#     { mime = "application/x-tar",           fg = "#55559D" },
#     { mime = "application/x-bzip",          fg = "#55559D" },
#     { mime = "application/x-bzip2",         fg = "#55559D" },
#     { mime = "application/x-7z-compressed", fg = "#55559D" },
#     { mime = "application/x-rar",           fg = "#55559D" },
#
#     { name = "*", fg = "#6969C0" },
#     { name = "*/", fg = "#F5F4F5" }
# ]