"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

[manager]
# cwd = { fg = "#842920" }
#
# hovered         = { fg = "#842920", bg = "#131216", bold = true, underline = true }
# preview_hovered = { underline = true }
#
# find_keyword  = { fg = "#7D25E5", italic = true }
# find_position = { fg = "#0E7FCD", bg = "reset", italic = true }
#
# marker_selected = { fg = "#7D25E5", bg = "#7D25E5" }
# marker_copied   = { fg = "#7D25E5", bg = "#7D25E5" }
# marker_cut      = { fg = "#842920", bg = "#842920" }
#
# tab_active   = { fg = "#131216", bg = "#AA97A6" }
# tab_inactive = { fg = "#AA97A6", bg = "#131216" }
# tab_width    = 1
#
border_style  = { fg = "#F86BD6" }

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#131216", bg = "#131216" }

mode_normal = { fg = "#131216", bg = "#842920", bold = true }
mode_select = { fg = "#131216", bg = "#7D25E5", bold = true }
# mode_unset  = { fg = "#131216", bg = "#1FBFC5", bold = true }
#
# progress_label  = { fg = "#FDEAF8", bold = true }
# progress_normal = { fg = "#AA97A6", bg = "#131216" }
# progress_error  = { fg = "#842920", bg = "#131216" }
#
# permissions_t = { fg = "#AA97A6" }
# permissions_r = { fg = "#7D25E5" }
# permissions_w = { fg = "#842920" }
# permissions_x = { fg = "#7D25E5" }
# permissions_s = { fg = "#AA97A6" }

# [input]
# border   = { fg = "#7D25E5" }
# title    = {}
# value    = {}
# selected = { reversed = true }
#
# [select]
# border   = { fg = "#AA97A6" }
# active   = { fg = "#0E7FCD" }
# inactive = {}
#
# [tasks]
# border  = { fg = "#AA97A6" }
# title   = {}
# hovered = { underline = true }
#
# [which]
# mask            = { bg = "#131216" }
# cand            = { fg = "#FDEAF8" }
# rest            = { fg = "#AA97A6" }
# desc            = { fg = "#0E7FCD" }
# separator       = "  "
# separator_style = { fg = "#AA97A6" }
#
# [help]
# on      = { fg = "#0E7FCD" }
# exec    = { fg = "#FDEAF8" }
# desc    = { fg = "#AA97A6" }
# hovered = { bg = "#AA97A6", bold = true }
# footer  = { fg = "#131216", bg = "#AA97A6" }
#
# [filetype]
# rules = [
#     { mime = "image/*", fg = "#1FBFC5" },
#
#     { mime = "video/*", fg = "#7544A1" },
#     { mime = "audio/*", fg = "#7D25E5" },
#
#     { mime = "application/zip",             fg = "#0E7FCD" },
#     { mime = "application/gzip",            fg = "#0E7FCD" },
#     { mime = "application/x-tar",           fg = "#0E7FCD" },
#     { mime = "application/x-bzip",          fg = "#0E7FCD" },
#     { mime = "application/x-bzip2",         fg = "#0E7FCD" },
#     { mime = "application/x-7z-compressed", fg = "#0E7FCD" },
#     { mime = "application/x-rar",           fg = "#0E7FCD" },
#
#     { name = "*", fg = "#7544A1" },
#     { name = "*/", fg = "#FDEAF8" }
# ]