filter = "vibrant"     # or "nord", "vibrant"
check_contrast = true
saturation = 45 # A little more "pop" for the G502 X aesthetic

[templates]
kitty = { template = "kitty.conf", target = "~/.config/kitty/conf.d/colors.conf" }
ghostty = { template = "ghostty", target = "~/.config/ghostty/themes/wal" }
foot = { template = "foot.ini", target = "~/.config/foot/foot.ini"}
fzf_bash = {template = "fzf_bash", target = "~/.cache/wallust/fzf_bash" }
fzf_fish = {template = "fzf.fish", target = "~/.config/fish/conf.d/wallust_fzf.fish" }
rofi = { template = "rofi.rasi", target = "~/.config/rofi/colors/wallust.rasi" }
vim = { template = "colors.vim", target = "~/.cache/colors.vim" }
nvim = { template = "neopywal.vim", target = "~/.cache/wallust/colors_neopywal.vim" }
waybar = { src = "waybar.css", dst = "~/.config/waybar/colors.css" }
xres = { template = "Xresources", target = "~/.config/x/Xresources.d/colors" }
yazi = { template = "yazi.toml", target = "~/.config/yazi/theme.toml" }
vscode = { src = 'vscode.json', dst = '~/.cache/wallust/colors.json' }
vscode2 = { src = 'vscode', dst = '~/.cache/wallust/colors' }
starship = { src = "starship.toml", dst = "~/.config/starship.toml" }
tmux = { src = "tmux.conf", dst = "~/.config/tmux/wallust.conf" }